before_script:
  - apk add --no-cache py-pip

stages:
  - deploy

variables:
  CONTAINER_IMAGE: sickrage/sickrage

  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:dind

deploy_docker_develop_arm32v7:
  stage: deploy
  image: docker:latest
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  script:
    - echo $CI_COMMIT_SHA
    - echo $CONTAINER_IMAGE
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build --network host --build-arg="SOURCE_COMMIT=$CI_COMMIT_SHA" -t $CONTAINER_IMAGE:$(cat sickrage/version.txt).arm32v7 -f Dockerfile.arm32v7 .
  only:
    - added_docker_arm_support
  except:
    - tags

deploy_docker_develop_arm64v8:
  stage: deploy
  image: docker:latest
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  script:
    - echo $CI_COMMIT_SHA
    - echo $CONTAINER_IMAGE
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build --network host --build-arg="SOURCE_COMMIT=$CI_COMMIT_SHA" -t $CONTAINER_IMAGE:$(cat sickrage/version.txt).arm64v8 -f Dockerfile.arm64v8 .
  only:
    - added_docker_arm_support
  except:
    - tags