before_script:
  - apk add --no-cache py-pip

stages:
  - deploy

variables:
  CONTAINER_IMAGE: sickrage/sickrage
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

cache:
  paths:
    - .cache/pip

services:
  - docker:dind

deploy_docker_master:
  stage: deploy
  image: docker:latest
  script:
    - echo $CI_COMMIT_SHA
    - echo $CONTAINER_IMAGE
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker pull $CONTAINER_IMAGE:latest
    - docker build --network host --build-arg="SOURCE_COMMIT=$CI_COMMIT_SHA" --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_IMAGE:$(cat sickrage/version.txt) -f Dockerfile .
  only:
    - testing-gitlab-cache
  except:
    - tags